### ISSUE TITLE
Missing links in multiple lines.

### ISSUE THREAD

**Issue by maxmironov** [bryanwoods/autolink-js#20] opened 2015-09-16 11:06 UTC
Actually I am not sure for a reason why links are absent, but
```
http://google.com
"http://google.com"
(http://google.com)
```
(all in single string) produces no links for me. Tested in Chrome 45.0.2454.85 m.

**Comment by bryanwoods** [comment] 2015-09-22 22:04
Hi @maxmironov -- I've added a test to reproduce this issue and pushed to a branch here: https://github.com/bryanwoods/autolink-js/commit/4ccec40bf61c51c2c67574e01c316bbbd8601fab

It seems to be working as expected, so I'm closing for now. Please feel free to open a new issue if you've found a bug or expected another result.

**Closed by bryanwoods** 2015-09-22 22:04 UTC

**Comment by maxmironov** [comment] 2015-09-25 08:50
Well, I believe all three occurences should be autolinked, shouldn't they?
